"""
DisruptionShield - RecoveryPlan Model
Records every automated recovery plan generated after a disruption.
"""

from datetime import datetime
from typing import Optional
from sqlalchemy import String, Integer, DateTime, Text, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from database import Base


class RecoveryPlan(Base):
    __tablename__ = "recovery_plans"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # FK → DisruptionLog
    disruption_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("disruption_logs.id", ondelete="CASCADE"), nullable=False
    )

    # JSON-serializable summary of all changes made
    changes_made: Mapped[str] = mapped_column(Text, nullable=False)  # Stored as JSON string

    # Summary narrative generated by Coordinator
    summary_text: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Tasks rescheduled count
    tasks_reprioritized: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Events rescheduled count
    events_rescheduled: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Time saved by smart rescheduling (minutes)
    time_recovered_minutes: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    # Relationship
    disruption = relationship("DisruptionLog", foreign_keys=[disruption_id], lazy="selectin")

    def to_dict(self) -> dict:
        import json
        try:
            changes = json.loads(self.changes_made) if self.changes_made else []
        except Exception:
            changes = self.changes_made

        return {
            "id": self.id,
            "disruption_id": self.disruption_id,
            "changes_made": changes,
            "summary_text": self.summary_text,
            "tasks_reprioritized": self.tasks_reprioritized,
            "events_rescheduled": self.events_rescheduled,
            "time_recovered_minutes": self.time_recovered_minutes,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
